### ISSUE TITLE
Proposal: Rename this repo

### ISSUE THREAD

**Issue by njhale** [kcp-dev/code-generator#3]
With the introduction of #2 (lister generation), this repo will house more than just client generation. I propose we change the repo name to something more generic -- e.g. `controller-tools` or `codegen` -- before it gets too much foot traffic.

**Comment by njhale** [comment]
cc @ncdc @fabianvf @varshaprasad96

**Comment by ncdc** [comment]
Makes sense. code-generator?

**Comment by njhale** [comment]
> Makes sense. code-generator?

That works for me. @ncdc could you perform the rename?

**Comment by ncdc** [comment]
Will do

**Comment by ncdc** [comment]
Rename done

**Comment by ncdc** [comment]
Make sure you update your `git remote` settings for your clones
